# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a49a7712f495df57e53970d9d7130f0e571c4bc7cce169f416d6389a53b657d57457057943c3af998053b1b699385eff3e481805d4224ad87e53da319a1209

test:
  secret_key_base: ec60ab039e08289abbcaa3656d8b26166d3367342c9b2f761facdab55574c0af58a0000a69c614bfc094cbd4bb10b37e8d4ee5af8e04b3c2cc33d7c4d52dc0e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
